### ISSUE TITLE
grunt error

### ISSUE THREAD

**Issue by kkrishnan90** [vikz91/generator-mongoose#13]
Running grunt to run the development server throws me an error like below

```
restgoose-test$ grunt
module.js:550
    throw err;
    ^

Error: Cannot find module 'findup-sync'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/nodejs/grunt-cli/bin/grunt:8:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

I have also installed all necessary node packages (both local as well as global) for grunt to work.

Any help on this is much appreciated !

**Comment by vikz91** [comment]
You should use npm start
