### ISSUE TITLE
crash using yo restgoose

### ISSUE THREAD

**Issue by EricBois** [vikz91/generator-mongoose#16]
_-----_     ╭──────────────────────────╮
    |       |    │   Welcome to the Rapid   │
    |--(o)--|    │    Rest API Generator    │
   `---------´   │   generator-restgoose2!  │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? Database Name myDb
? Database Host localhost
? Database Port 27017
? Database User 
? Database Password [hidden]
Reinitialized existing Git repository in /home/burn/nodejs/.git/
events.js:173
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /usr/lib/node_modules/generator-restgoose/generators/app/templates/.gitignore
    at EditionInterface.exports.copy (/usr/lib/node_modules/generator-restgoose/node_modules/mem-fs-editor/lib/actions/copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (/usr/lib/node_modules/generator-restgoose/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at module.exports.writing (/usr/lib/node_modules/generator-restgoose/generators/app/index.js:85:21)
    at Object.<anonymous> (/usr/lib/node_modules/generator-restgoose/node_modules/yeoman-generator/lib/index.js:424:27)
    at /usr/lib/node_modules/generator-restgoose/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/lib/node_modules/generator-restgoose/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/lib/node_modules/generator-restgoose/node_modules/yeoman-generator/lib/index.js:425:13)
    at processImmediate (timers.js:637:19)
Emitted 'error' event at:
    at Immediate.setImmediate (/usr/lib/node_modules/generator-restgoose/node_modules/yeoman-generator/lib/index.js:433:22)
    at processImmediate (timers.js:637:19)

**Comment by alwindeleon** [comment]
Go to: /usr/local/lib/node_modules/generator-restgoose/generators/app/templates
change .npmignore to .gitignore

**Comment by vikz91** [comment]
This has been resolved in the new release. Please update. Again, thanks for pointing out.
