### ISSUE TITLE
l.responseCallback is not a function

### ISSUE THREAD

**Issue by gerardob** [vikz91/generator-mongoose#8]
TypeError: l.responseCallback is not a function
    at Object.api.test (/home/it/projects/connectfy/apiObjects/testing.js:116:12)
    at router.get (/home/it/projects/connectfy/api/testing.js:219:10)
    at Layer.handle [as handle_request] (/home/it/projects/connectfy/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/it/projects/connectfy/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/it/projects/connectfy/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/it/projects/connectfy/node_modules/express/lib/router/layer.js:95:5)
    at /home/it/projects/connectfy/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/it/projects/connectfy/node_modules/express/lib/router/index.js:335:12)
    at next (/home/it/projects/connectfy/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/it/projects/connectfy/node_modules/express/lib/router/index.js:174:3)
    at router (/home/it/projects/connectfy/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/it/projects/connectfy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/it/projects/connectfy/node_modules/express/lib/router/index.js:317:13)
    at /home/it/projects/connectfy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/it/projects/connectfy/node_modules/express/lib/router/index.js:335:12)
    at next (/home/it/projects/connectfy/node_modules/express/lib/router/index.js:275:10)

the error is the body at http://localhost:3000/api/xxxxx/test

**Comment by vikz91** [comment]
Thanks for the heads up. I have patched this fix in the latest version : 0.2.51 .
Please update your restgoose  generator to the latest.
